services:
  archiveTeamWarrior:
    image: atdr.meo.ws/archiveteam/warrior-dockerfile
    container_name: archiveTeamWarrior
    hostname: archiveTeamWarrior
    environment:
      - DOWNLOADER:${DOWNLOADER}
      - SELECTED_PROJECT:${SELECTED_PROJECT}
    ports:
      - "8001:8001"
    restart: always
    volumes:
      - ./projects:/home/warrior/projects
