version: "3"
services:
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - TZ=America/NewYork
      - PUID=1000
      - PGID=1000
      - UMASK=002
    volumes:
      - ./radarr:/config
      - /media/Media/Movies:/movies
      - /home/dan/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - TZ=America/NewYork
      - PUID=1000
      - PGID=1000
      - UMASK=002
    volumes:
      - ./sonarr:/config
      - /media/Media/TV:/tv
      - /home/dan/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr
    container_name: lidarr
    environment:
      - TZ=America/NewYork
      - PUID=1000
      - PGID=1000
      - UMASK=002
    volumes:
      - ./lidarr:/config
      - /media/Media/Music:/music
      - /home/dan/downloads:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - TZ=America/NewYork
      - PUID=1000
      - PGID=1000
      - UMASK=002
    volumes:
      - ./prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  nzbget:
    image: lscr.io/linuxserver/nzbget
    container_name: nzbget
    environment:
      - TZ=America/NewYork
      - PUID=1000
      - PGID=1000
    volumes:
      - ./nzbget/config:/config
      - ./nzbget/intermediate:/intermediate
      - /home/dan/downloads:/downloads
    ports:
      - 6789:6789
    restart: unless-stopped

  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    environment:
      - TZ=America/NewYork
      - PLEX_UID=1000
      - PLEX_GID=1000
      - PLEX_CLAIM=<claimToken>
    network_mode: host
    volumes:
      - ./plex:/config
      - /media/Media:/data
    devices:
      - "/dev/dri:/dev/dri"
